# Import libraries

In [1]:
import numpy as np

# Input the sequence

In [17]:
seq1=input("Enter seq1 : ")
seq2=input("Enter seq2 : ")

Enter seq1 : MNALQM
Enter seq2 : NALMSQA


In [18]:
#seq1="MNALQM"
#seq2="NALMSQA"

# Make the matrix

In [3]:
main_matrix=np.zeros((len(seq1)+1,len(seq2)+1))

In [4]:
check_matrix=np.zeros((len(seq1),len(seq2)))

# Scoring

In [5]:
match_score=1
mismatch_score=-1
gap_score=-2

# Filling the check matrix 

In [6]:
for i in range(len(seq1)):
    for j in range(len(seq2)):
        if seq1[i] == seq2[j]:
            check_matrix[i][j]= match_score
        else:
            check_matrix[i][j]= mismatch_score

In [7]:
print(check_matrix)

[[-1. -1. -1.  1. -1. -1. -1.]
 [ 1. -1. -1. -1. -1. -1. -1.]
 [-1.  1. -1. -1. -1. -1.  1.]
 [-1. -1.  1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.  1. -1.]
 [-1. -1. -1.  1. -1. -1. -1.]]


# Needleman wunsch algorithm

## 1. Initialization

In [8]:
for i in range(len(seq1)+1):
    main_matrix[i][0] = i*gap_score
for j in range(len(seq2)+1):
    main_matrix[0][j] = j * gap_score

## 2. Fill the matrix

In [9]:
for i in range(1,len(seq1)+1):
    for j in range(1,len(seq2)+1):
        main_matrix[i][j] = max(main_matrix[i-1][j-1]+check_matrix[i-1][j-1],
                                main_matrix[i-1][j]+gap_score,
                                main_matrix[i][j-1]+ gap_score)


In [10]:
print(main_matrix)

[[  0.  -2.  -4.  -6.  -8. -10. -12. -14.]
 [ -2.  -1.  -3.  -5.  -5.  -7.  -9. -11.]
 [ -4.  -1.  -2.  -4.  -6.  -6.  -8. -10.]
 [ -6.  -3.   0.  -2.  -4.  -6.  -7.  -7.]
 [ -8.  -5.  -2.   1.  -1.  -3.  -5.  -7.]
 [-10.  -7.  -4.  -1.   0.  -2.  -2.  -4.]
 [-12.  -9.  -6.  -3.   0.  -1.  -3.  -3.]]


## 3. Traceback

In [11]:
align1=""
align2=""

In [12]:
l1=len(seq1)
l2=len(seq2)

In [15]:
while(l1 >0 and l2 > 0):

    if (l1 >0 and l2 > 0 and main_matrix[l1][l2] == main_matrix[l1-1][l2-1]+ check_matrix[l1-1][l2-1]):

        align1 = seq1[l1-1] + align1
        align2 = seq2[l2-1] + align2

        l1 = l1 - 1
        l2 = l2 - 1
    
    elif(l1 > 0 and main_matrix[l1][l2] == main_matrix[l1-1][l2] + gap_score):
        align1 = seq1[l1-1] + align1
        align2 = "-" + align2

        l1 = l1 -1
    else:
        align1 = "-" + align1
        align2 = seq2[l2-1] + align2

        l2 = l2 - 1


# Result

In [16]:
print(align1)
print(align2)

NAL--QM
NALMSQA
